export const BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8080';

export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/api/login`,
  SIGNUP_USER: `${BASE_URL}/api/signup/user`,
  SIGNUP_DOCTOR: `${BASE_URL}/api/signup/doctor`,
  SIGNUP_PATIENT: `${BASE_URL}/api/signup/patient`,
  SIGNUP_PHARMACIST: `${BASE_URL}/api/signup/pharmacist`,
  SIGNUP_ADMIN: `${BASE_URL}/api/signup/admin`,
  GET_PATIENT_BY_ID: (id) => `${BASE_URL}/api/patients/${id}`,
  GET_DOCTOR_BY_ID: (id) => `${BASE_URL}/api/doctors/${id}`,
  UPDATE_PATIENT_PROFILE: (id) => `${BASE_URL}/api/patients/${id}`,
  UPDATE_DOCTOR_PROFILE: (id) => `${BASE_URL}/api/doctors/${id}`,
  GET_AVAILABLE_APPOINTMENTS: `${BASE_URL}/api/appointments/available`,
  CREATE_APPOINTMENT_REQUEST: `${BASE_URL}/api/appointments/request`,
  GET_OUTCOME_RECORDS_BY_PATIENT_ID: (id) => `${BASE_URL}/api/outcomes/patients/${id}`,
  GET_BOOKED_APPOINTMENTS_BY_DOCTOR_ID: (id) => `${BASE_URL}/api/appointments/doctors/booked/${id}`,
  CHANGE_PASSWORD: (id) => `${BASE_URL}/api/users/${id}/change-password`, 
  GET_ALL_DOCTORS: `${BASE_URL}/api/doctors`,
  GET_AVAILABLE_SLOTS: (doctorId, date) => `${BASE_URL}/api/availability/full?doctorId=${doctorId}&date=${date}`,
  CHECK_DOCTOR_AVAILABILITY_EXISTS: (doctorId) => `${BASE_URL}/api/availability/doctor/${doctorId}/exists`,
  GET_DOCTOR_AVAILABILITY: (doctorId) => `${BASE_URL}/api/availability/doctor/${doctorId}`,
  CREATE_AVAILABILITY: `${BASE_URL}/api/availability`,
  GET_COMPLETED_APPOINTMENTS_BY_DOCTOR_ID: (id) => `${BASE_URL}/api/appointments/doctors/completed/${id}`,
  CREATE_OUTCOME_RECORD: `${BASE_URL}/api/outcomes`,
  GET_APPOINTMENTS_BY_PATIENT_ID: (patientId) => `${BASE_URL}/api/appointments/patients/${patientId}`,
  CANCEL_APPOINTMENT: (appointmentId) => `${BASE_URL}/api/appointments/${appointmentId}/cancel`,
  RESCHEDULE_APPOINTMENT: `${BASE_URL}/api/appointments/reschedule`,
  UPDATE_APPOINTMENT_STATUS: (appointmentId, status) => `${BASE_URL}/api/appointments/${appointmentId}/status?status=${status}`,
  GET_REQUESTED_APPOINTMENTS_BY_DOCTOR_ID: (doctorId) => `${BASE_URL}/api/appointments/doctors/requested/${doctorId}`,
  DELETE_APPOINTMENT: (appointmentId) => `${BASE_URL}/api/appointments/${appointmentId}`,
  GET_PHARMACIST_BY_ID: (id) => `${BASE_URL}/api/pharmacists/${id}`,
  GET_PENDING_OUTCOMES_FOR_PHARMACIST: `${BASE_URL}/api/outcomes/pharmacist/pending`,
  UPDATE_PRESCRIPTION_STATUS: (id, status) => `${BASE_URL}/api/outcomes/${id}/status?prescriptionStatus=${status}`,
  GET_ADMIN_BY_ID: (id) => `${BASE_URL}/api/admins/${id}`,
  GET_ALL_PHARMACISTS: `${BASE_URL}/api/pharmacists`,
  GET_ALL_PATIENTS: `${BASE_URL}/api/patients`,
  UPDATE_PHARMACIST_PROFILE: (id) => `${BASE_URL}/api/pharmacists/${id}`,
  UPDATE_ADMIN_PROFILE: (id) => `${BASE_URL}/api/admins/${id}`,
  GET_INACTIVE_USERS: `${BASE_URL}/api/admins/inactive-users`,  
  ACTIVATE_USER: `${BASE_URL}/api/admins/activate-account`,     
  DELETE_USER: `${BASE_URL}/api/admins/delete-account`,
  GET_S3_UPLOAD_URL: `${BASE_URL}/api/s3/upload-url`
};
